# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'sonicSega' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for sonicSega

  target 'sonicSegaTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'sonicSegaUITests' do
    # Pods for testing
  end

   pod 'FirebaseCore'
   pod 'FirebaseAuth
 
end
